# ----------------------------------------------------------------------------------------
#
# Copyright (c) 2023, WSO2 LLC. (https://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC. and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained
# herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
# You may not alter or remove any copyright or other notice from copies of this content.
#
# ----------------------------------------------------------------------------------------

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "ob-pattern-1.resource.prefix" . }}-obiam-ingress
  namespace : {{ .Release.Namespace }}
{{- if .Values.wso2.deployment.ob.iam.ingress.management.annotations }}
  annotations:
{{ toYaml .Values.wso2.deployment.ob.iam.ingress.management.annotations | indent 4 }}
{{- end }}
spec:
  tls:
  - hosts:
      - {{ .Values.wso2.deployment.ob.iam.ingress.management.hostname }}
  rules:
  - host: {{ .Values.wso2.deployment.ob.iam.ingress.management.hostname }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ template "ob-pattern-1.resource.prefix" . }}-obiam-service
              port:
                number: 9446
